import { jsPDF } from 'jspdf';
import type { Summary, Article, VocabData } from '../types';

function sanitizeFilename(filename: string): string {
  return filename
    .replace(/[^a-z0-9\s-]/gi, '_')
    .replace(/\s+/g, '_')
    .replace(/_+/g, '_')
    .substring(0, 50)
    .replace(/^_|_$/g, '');
}

function addFooter(doc: jsPDF, pageWidth: number): void {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(150, 150, 150);

    const footerY = doc.internal.pageSize.getHeight() - 15;
    const dateText = `Generated by AI Article Summarizer on ${new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })}`;
    const dateWidth = doc.getTextWidth(dateText);
    doc.text(dateText, (pageWidth - dateWidth) / 2, footerY);

    const poweredText = 'Powered by Google Gemini AI';
    const poweredWidth = doc.getTextWidth(poweredText);
    doc.text(poweredText, (pageWidth - poweredWidth) / 2, footerY + 5);
  }
}

export async function exportSummaryPDF(summary: Summary, article: Article): Promise<void> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(article.title, maxWidth);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 7 + 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(100, 100, 100);
  doc.text(`Author: ${article.author} | Source: ${article.siteName}`, margin, y);
  y += 6;

  doc.setFontSize(9);
  doc.setTextColor(26, 115, 232);
  const urlLines = doc.splitTextToSize(article.url, maxWidth);
  doc.text(urlLines, margin, y);
  y += urlLines.length * 4 + 10;

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('Summary', margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 51, 51);

  const cleanSummary = summary.summary.replace(/\*\*(.*?)\*\*/g, '$1');
  const summaryLines = doc.splitTextToSize(cleanSummary, maxWidth);
  summaryLines.forEach((line: string) => {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.text(line, margin, y);
    y += 6;
  });

  y += 8;

  if (summary.bulletPoints.length > 0) {
    if (y > 250) { doc.addPage(); y = 20; }

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text('Key Points', margin, y);
    y += 8;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 51, 51);

    summary.bulletPoints.forEach((point) => {
      const cleanPoint = point.replace(/\*\*(.*?)\*\*/g, '$1');
      const bulletLines = doc.splitTextToSize(cleanPoint, maxWidth - 5);
      bulletLines.forEach((line: string, index: number) => {
        if (y > 275) { doc.addPage(); y = 20; }
        if (index === 0) {
          doc.text('•', margin, y);
          doc.text(line, margin + 5, y);
        } else {
          doc.text(line, margin + 5, y);
        }
        y += 6;
      });
      y += 2;
    });
  }

  addFooter(doc, pageWidth);
  doc.save(`${sanitizeFilename(article.title)}_summary.pdf`);
}

export async function exportVocabularyPDF(vocabData: VocabData): Promise<void> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  const titleLines = doc.splitTextToSize(`Vocabulary: ${vocabData.articleTitle}`, maxWidth);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 7 + 6;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(100, 100, 100);
  doc.text(`Language: ${vocabData.language} | Level: ${vocabData.cefrLevel}`, margin, y);
  y += 7;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(26, 115, 232);
  const urlLines = doc.splitTextToSize(vocabData.articleUrl, maxWidth);
  doc.text(urlLines, margin, y);
  y += urlLines.length * 4 + 10;

  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  vocabData.items.forEach((item) => {
    if (y > 270) { doc.addPage(); y = 20; }

    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(32, 33, 36);
    doc.text(item.word, margin, y);

    const badgeText = vocabData.cefrLevel;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(21, 87, 176);
    const badgeWidth = doc.getTextWidth(badgeText);
    doc.text(badgeText, pageWidth - margin - badgeWidth, y);
    y += 6;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(26, 115, 232);
    doc.text(item.translation, margin, y);
    y += 6;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(95, 99, 104);

    const exampleLines = doc.splitTextToSize(item.example, maxWidth);
    exampleLines.forEach((line: string) => {
      if (y > 275) { doc.addPage(); y = 20; }
      doc.text(line, margin, y);
      y += 5;
    });

    const translationLines = doc.splitTextToSize(item.example_translation, maxWidth);
    translationLines.forEach((line: string) => {
      if (y > 275) { doc.addPage(); y = 20; }
      doc.text(line, margin, y);
      y += 5;
    });

    y += 3;
    doc.setDrawColor(220, 220, 220);
    doc.line(margin, y, pageWidth - margin, y);
    y += 7;
  });

  addFooter(doc, pageWidth);
  doc.save(`${sanitizeFilename(vocabData.articleTitle)}_vocab_${vocabData.cefrLevel}_${vocabData.language}.pdf`);
}
